events {
    worker_connections 1024;
}

http {
    # 127.0.0.11 est le résolveur DNS interne par défaut de Docker
    resolver 127.0.0.11 valid=30s;

    upstream template_upstream { # change api name
        server template:3000; # change api name and port
    }

    server {
        listen 80;
        server_name template.development.mairie360.fr; # change api name

        location / {
            # On utilise une variable pour que Nginx accepte la config
            # même si le backend n'est pas résolu instantanément
            set $backend "http://template_upstream"; # change api name
            proxy_pass $backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
